title = "Fund The Code!"
baseURL = "https://fundthecode.org"
tags = ["funding", "free software", "open source", "event"]
languageCode = "fr-Fr"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

defaultContentLanguage = "fr"

[Author]
    name = "Bastien Guerry"
    profile = "https://bzg.fr"

[Params]
    author = "Bastien Guerry"
    logoBig = "/images/fundthecode-logo.png"
    logoSmall = "/images/fundthecode-logo-small.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/fundthecode-logo.png"
    email = "contact@fundthecode.org"
    highlightJS = false
    copyright = false
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[languages]
  [languages.fr]
    weight = 1
    [languages.fr.params]
      tagline = "Le logiciel libre ne pousse pas dans les arbres."
      description = "Soirées de dons pour des logiciels libres"
  [languages.en]
    weight = 2
    [languages.en.params]
      tagline = "Free Softwares Do Not Grow on Trees."
      description = "Fund The Code: Donate to Free Softwares Through Live Events"

[[languages.en.menu.main]]
    name = "Get donations"
    url  = "/en/receive"
    weight = 1
[[languages.en.menu.main]]
    name = "Sponsor us"
    url  = "/en/sponsor"
    weight = 2
[[languages.en.menu.main]]
    name = "Join the event"
    url  = "/en/join"
    weight = 3
[[languages.en.menu.main]]
    name = "More"
    url  = "/en/more"
    weight = 4
[[languages.en.menu.main]]
    name = "> FR"
    url  = "/"
    weight = 5

[[languages.fr.menu.main]]
    name = "Être soutenu"
    url  = "/soutenu"
    weight = 1
[[languages.fr.menu.main]]
    name = "Soutenir"
    url  = "/soutenir"
    weight = 2
[[languages.fr.menu.main]]
    name = "Venir"
    url  = "/venir"
    weight = 3
[[languages.fr.menu.main]]
    name = "Plus"
    url  = "/plus"
    weight = 4
[[languages.fr.menu.main]]
    name = "> EN"
    url  = "/en"
    weight = 5
