title = "Fund The Code!"
baseURL = "https://fundthecode.org"
tags = ["funding", "free software", "open source", "event"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Author]
    name = "Bastien Guerry"
    profile = "https://bzg.fr"

[Params]
    author = "Bastien Guerry"
    logoBig = "/images/fundthecode-logo.png"
    logoSmall = "/images/fundthecode-logo-small.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/fundthecode-logo.png"
    email = "contact@fundthecode.org"
    highlightJS = false
    copyright = false
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

defaultContentLanguage = "fr"

[languages]
  [languages.en]
    weight = 1
    [languages.en.params]
      tagline = "Open Source Does Not Grow on Trees."
      description = "Fund The Code: Donate to Free Software Through Live Events"
  [languages.fr]
    weight = 2
    [languages.fr.params]
      tagline = "Le logiciel libre ne pousse pas dans les arbres."
      description = "Soirées de dons pour des logiciels libres"

[[languages.en.menu.main]]
    name = "Why?"
    url  = "/why"
    weight = 1
[[languages.en.menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[languages.en.menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3
[[languages.en.menu.main]]
    name = "> FR"
    url  = "/fr"
    weight = 4

[[languages.fr.menu.main]]
    name = "Pourquoi ?"
    url  = "/fr/why"
    weight = 1
[[languages.fr.menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[languages.fr.menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 3
[[languages.fr.menu.main]]
    name = "> EN"
    url  = "/"
    weight = 4
