#+title: Foire Aux Questions
#+date: 2018-11-29

** Qu'est-ce qu'un événement /Fund The Code/ ?

 C'est un événement de soutien financier pour des [[https://fr.wikipedia.org/wiki/Logiciel_libre][logiciels libres]] et
 un moment de rencontre entre des mainteneurs, des contributeurs et des
 vrais gens.

** Quels projets peuvent être soutenus ?

Tout projet logiciel peut être soutenu pourvu qu'il soit publié sous
une [[https://fr.wikipedia.org/wiki/Licence_libre][licence libre]].

** Comment soumettre un projet pour /Fund The Code/ 2018 ?

L'appel à projets durera *du 1er au 31 décembre 2018 à 23h59* et vous
pourrez soumettre votre projet [[https://fundthecode.typeform.com/to/XmXL73][via ce formulaire]].

** Comment se déroule un événement /Fund The Code/ ?

Le format « standard » est celui-ci :

- en amont de la soirée, des soutiens financiers sont mobilisés
  (entreprises, associations, etc.) ;
- pendant l'événement, les porteurs de projets présentent leurs
  projets et expliquent pourquoi ils sollicitent des dons ;
- l'audience est munie d'un moyen de "voter" et de répartir l'argent
  récolté : billets de jeu, jetons, etc. ;
- chaque participant répartit la somme qu'il a reçue en votant pour un
  ou plusieurs projets présentés ;
- les organisateurs annoncent les résultats et s'occupent des
  transactions (i.e. virements ou autre.)

Toutes les variations sont possibles, tant que la soirée est centrée
sur les dons faits à des projets libres.

*** Les organisateurs peuvent-ils prélever un pourcentage sur les dons ?

Non, tout l'argent donné par les soutiens financiers doit être
redistribué.  Les sommes retenues sont celles dédiées à l'événement
lui-même : boissons, nourriture, etc. et elles doivent être clairement
indiquées aux participants avant et après l'événement.

*** Comment se passe la sélection des projets ?

Chaque équipe organisatrice décide de mettre en place une sélection ou
non, et elle définit les modalités de cette sélection. Le seul critère
obligatoire est de ne sélectionner que des projets qui contribuent de
façon claire et publique à des projets de logiciels libres.

*** Combien d'événements /Fund The Code/ ont déjà eu lieu ?

Les trois premiers événements s'appelaient des « Hackadons ».

- Le premier a eu lieu le 11 décembre 2013 à simplon.co, initié par
  [[https://bzg.fr][Bastien Guerry]] et openfunding.org.
- Le deuxième a eu lieu le 11 décembre 2014, organisé par
  [[http://librefunding.org/][librefunding.org]] et [[http://www.withoutmodel.com/][withoutmodel.com]].  Voir [[https://hackadon.org/videos2014.html][les vidéos]].
- Les suivants ont eu lieu 11 décembre 2015, organisés par
  [[http://www.withoutmodel.com][withoutmodel.com]] et [[http://labomedia.org][labomedia.org]].  Voir [[https://hackadon.org/videos2015.html][les vidéos]].
** Qui peut organiser un événement /Fund The Code/ ?

Toute structure : association, entreprise, etc.  La structure reçoit
les dons des soutiens financiers et assure leur répartition auprès des
projets participants.  N'hésitez pas à nous contacter si vous voulez
en organiser un.

** Qui peut assister à un événement /Fund The Code/ ?

Tout le monde.  Les événements /Fund The Code/ doivent être des
événements publics, gratuits, ouverts à tous en fonction des places
disponibles.

