#+title: Vous voulez soutenir le libre financièrement ?
#+date: 2018-11-29

*Nous recherchons des sponsors* : associations, entreprises ou toute
structure voulant soutenir le mouvement du logiciel libre en donnant
directement à ceux qui y contribuent.

Lors de la soirée /Fund The Code/, l'argent des sponsors sera remis aux
participants sous forme de jetons et chaque participant pourra voter
pour les projets qui l'ont interpelé.

Les organisateurs s'occupent de recevoir les dons des sponsors et de
faire les dons pour les projets.

*Vous souhaitez devenir sponsors* ?  Expliquez-nous comment et pourquoi
via [[https://fundthecode.typeform.com/to/FGRfcl][ce formulaire]] !

*Pourquoi sponsoriser Fund the Code ?*

- Votre structure utilise des logiciels libres mais ne sait pas trop par où commencer pour donner : à qui ? comment ? pourquoi ?
- Vous voulez rencontrer des porteurs de projets libres et les aider directement en connaissant leurs besoins.
- Vous souhaitez afficher votre soutien au mouvement du libre plus largement qu'en donnant à tel ou tel projet.
- Vous souhaitez rencontrer d'autres structures qui soutiennent financièrement le logiciel libre pour connaître leurs motivations.

Pour toute question, n'hésitez pas à [[/#contact][nous contacter]] !
